#
# General TradeConfig
#

aws:
  profileName: "gncloud"
  region: "ap-northeast-2"
  ecs:
    clusterId: "systom"
    definition:
      name: "systom"
      version: "9"
      container:
        signal: "systom-signal"
        executor: "systom-executor"
  cognito:
    userPoolId: "ap-northeast-2_8UlVuFFva"
    clientId: "4km83jbt1d6pg415q4ieqt41b0"


spring:
  datasource:
    url: "jdbc:mysql://gncloudinstance.cygcygiwvnc8.ap-northeast-2.rds.amazonaws.com:3306/systom?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul"
    username: "gncloud"
    password: "gnc=1151"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

backtest:
    host: "tcp://52.78.216.101:2376"
    image: "868448630378.dkr.ecr.ap-northeast-2.amazonaws.com/cctrader"
    apiServerUrl: "http://13.125.73.226:20000"
    timezone: "Asia/Seoul"
    container:
          readTimeout: 300000
          connectTimeout: 10000
    initCashKrw: 100000000
    initCashUsdt: 10000

scheduler:
  isMonthCalculation: "false"
  isPaymentDelayStatus: "false"
  isLiveTaskObserve: "true"
  isNotification: "false"
  isCurrencyRateUpdate: "false"

invest:
  timezone: "Asia/Seoul"
  initCommission: 40
  maxFriendsSaleCount: 5
  start:
    hour: "00"
    minute: "00"
    second: "00"
  end:
    hour: "23"
    minute: "59"
    second: "59"

notifications:
  telegramUrl: "https://bacl02xrl3.execute-api.ap-northeast-2.amazonaws.com/v1/message"

task:
  maxRetry: 3

friends:
  maxSize: 5