#
# General Config
#


aws:
  ProfileName: "gncloud"
  region:
  ecs:
    clusterId: "coincloud"
    difinition:
      name: "tradebot"
      version: "6"
      container: "tradebot"
  congnito:
    poolId:
    clientappId:
    fedPoolId:
    customDomain:


spring:
  datasource:
    url: "jdbc:mysql://gncloudinstance.cygcygiwvnc8.ap-northeast-2.rds.amazonaws.com:3306/coincloud"
    username: "gncloud"
    password: "gnc=1151"
    driver-class-name: "com.mysql.jdbc.Driver"

