#
# General Config
#


aws:
  ProfileName: "gncloud"
  region:
  ecs:
    clusterId: "coincloud"
    difinition:
      name: "tradebot"
      version: "8"
      container: "tradebot"
  cognito:
    poolId: ""
    clientappId: ""
    fedPoolId: ""
    customDomain: ""
  stream:
    region: "ap-northeast-2"
    name: "order_stream"
    shardId: "shard-000000000000"
    limit: 1000


spring:
  devtools:
    livereload: true
  datasource:
    url: "jdbc:mysql://gncloudinstance.cygcygiwvnc8.ap-northeast-2.rds.amazonaws.com:3306/coincloud?useUnicode=true&characterEncoding=utf8"
    username: "gncloud"
    password: "gnc=1151"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

